---
- hosts: 127.0.0.1
  become: true
  tasks:
    - apt: update_cache=yes

    - name: Install Pip
      apt: name=python3-pip state=present

    - name: upgarde pip to the latest
      pip:
        name: pip
        executable: pip3
        extra_args: --user
        state: latest
      become: true
      become_method: su
      become_user: codio
      become_flags: '-s /bin/sh'

    - name: Installing jupyter nbconvert
      pip:
        name: nbconvert
        version: 5.6.1
        executable: pip3
        extra_args: --user
      become: true
      become_method: su
      become_user: codio
      become_flags: '-s /bin/sh'

    - name: Installing notebook and nbgrader
      pip:
        name: notebook, nbgrader, numpy, scipy, matplotlib
        executable: pip3
        extra_args: --user
      become: true
      become_method: su
      become_user: codio
      become_flags: '-s /bin/sh'

    - name: Downgrade jupyter_client==6.1.12
      pip:
        name: jupyter_client
        version: 6.1.12
        executable: pip3
        extra_args: --user
      become: true
      become_method: su
      become_user: codio
      become_flags: '-s /bin/sh'


    - name: Systemd for jupyter
      copy: src=jupyter.service dest=/etc/systemd/system/jupyter.service
      when: ansible_distribution_version >= "16.04"

    - name: jupyter restarted
      systemd:
        enabled: yes
        state: restarted
        daemon_reload: yes
        name: jupyter
      when: ansible_distribution_version >= "16.04"
