---
- hosts: 127.0.0.1
  become: true

  tasks:
    - name: Add nodesource repository
      shell: curl -fsSL https://deb.nodesource.com/setup_22.x | sudo bash -

    - name: Add Yarn keyring
      shell: curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/yarnkey.gpg

    - name: Add Yarn APT repository
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list > /dev/null

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - nodejs
          - build-essential
          - yarn
          - systemd
          - zip
          - bubblewrap
        state: present

    # Install Opam
    - name: Check opam installer exists
      stat:
        path: ./opam-2.4.1-x86_64-linux
      register: opam_installer

    - name: Get Opam
      get_url:
        url: https://github.com/ocaml/opam/releases/download/2.4.1/opam-2.4.1-x86_64-linux
        dest: ./opam-2.4.1-x86_64-linux
        mode: '0755'
        checksum: "sha256:30da8eb20c8f4cfd3818db867d85f26df1ca5ca27cb25910c0235c5a02e12d3b"
      when: not opam_installer.stat.exists

    # - name: Add Opam repository
    #   shell: install ./opam-2.4.1-x86_64-linux /usr/local/bin/opam
    - name: Install opam binary
      copy:
        src: /usr/local/src/opam-2.4.1-x86_64-linux
        dest: /usr/local/bin/opam
        mode: '0755'
        owner: root
        group: root
        remote_src: true

    # Jeroo
    - name: Jeroo checkout
      become: yes
      become_user: codio
      git:
        repo: 'https://github.com/codio/jeroo.git'
        dest: /home/codio/jeroo/jeroo
        update: yes
        force: yes
        version: master

    # - copy: src=jeroo.prod.conf.ts dest=/home/codio/jeroo/jeroo/src/environments/environment.prod.ts
    - copy:
        src: jeroo.prod.conf.ts
        dest: /home/codio/jeroo/jeroo/src/environments/environment.prod.ts
        owner: codio
        group: codio
        mode: '0644'

    - copy: src=scripts/jeroo-opam.sh dest=/tmp/jeroo-opam.sh mode=0755
    - copy: src=scripts/yarn-jeroo.sh dest=/tmp/yarn-jeroo.sh mode=0755

    - name: Yarn jeroo build compiler
      shell: sh /tmp/jeroo-opam.sh
      become: yes
      become_user: codio

    - name: jeroo - yarn install
      become: yes
      become_user: codio
      shell: yarn install
      args:
        chdir: /home/codio/jeroo/jeroo

    - name: Yarn jeroo build
      shell: sh /tmp/yarn-jeroo.sh
      become: yes
      become_user: codio

    # Jeroo server
    - name: Jeroo server checkout
      become: yes
      become_user: codio
      git:
        repo: 'https://github.com/codio/jeroo-server.git'
        dest: /home/codio/jeroo/jeroo-server
        update: yes
        force: yes
        version: master

    - copy: src=jeroo-server.conf.json dest=/home/codio/jeroo/jeroo-server/config.json
    - copy: src=scripts/yarn-jeroo-server.sh dest=/tmp/yarn-jeroo-server.sh mode=0755

    - name: jeroo server - yarn install
      become: yes
      become_user: codio
      shell: yarn install
      args:
        chdir: /home/codio/jeroo/jeroo-server

    - name: Build jeroo-server
      shell: sh /tmp/yarn-jeroo-server.sh
      become: yes
      become_user: codio

    - copy: src=scripts/jeroo-server.sh dest=/home/codio/jeroo/jeroo-server/jeroo-server.sh mode=0755
    # - copy: src=systemd/jeroo-server.service dest=/etc/systemd/system/jeroo-server.service
    - copy:
        src: systemd/jeroo-server.service
        dest: /etc/systemd/system/jeroo-server.service
        owner: root
        group: root
        mode: '0644'

    # - service: name=jeroo-server state=restarted enabled=true
    - systemd:
        name: jeroo-server
        enabled: true
        state: restarted
        daemon_reload: true


- hosts: 127.0.0.1
  become: true
  roles:
    - role: jdauphant.nginx
      nginx_sites:
        jeroo:
          - listen 7501
          - client_max_body_size 150m
          - index index.html
          - location / {
              root /home/codio/jeroo/jeroo/dist/jeroo;
              try_files $uri $uri/ /index.html;
            }
          - location ^~ /jeroo-server-service/ {
              proxy_pass http://127.0.0.1:7500/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_http_version 1.1;
              proxy_cache off;
              proxy_buffering off;
            }
